// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObj.Models;

public partial class Blog
{
    [Key]
    [Column("BlogID")]
    [StringLength(20)]
    public string BlogId { get; set; }

    [Required]
    public string Content { get; set; }

    [Column("Create_at", TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [Column("Create_by")]
    [StringLength(20)]
    public string CreateBy { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Update_by")]
    [StringLength(20)]
    public string UpdateBy { get; set; }

    [Column("Delete_at", TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [Column("Delete_by")]
    [StringLength(20)]
    public string DeleteBy { get; set; }

    public bool? Status { get; set; }

    [Required]
    [StringLength(100)]
    public string Title { get; set; }

    [Column("Img_url")]
    public string ImgUrl { get; set; }

    [InverseProperty("Blog")]
    public virtual ICollection<RefBogsFeedback> RefBogsFeedbacks { get; set; } = new List<RefBogsFeedback>();
}