// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObj.Models;

[Table("Entertain")]
public partial class Entertain
{
    [Key]
    [Column("EnID")]
    [StringLength(20)]
    public string EnId { get; set; }

    [Required]
    [Column("Img_url")]
    public string ImgUrl { get; set; }

    public bool? Status { get; set; }

    [InverseProperty("En")]
    public virtual ICollection<RefProductImg> RefProductImgs { get; set; } = new List<RefProductImg>();
}