// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObj.Models;

[Table("Feedback")]
public partial class Feedback
{
    [Key]
    [Column("FeedbackID")]
    [StringLength(20)]
    public string FeedbackId { get; set; }

    [Column("ReplyID")]
    [StringLength(20)]
    public string ReplyId { get; set; }

    [StringLength(80)]
    public string Description { get; set; }

    public int Point { get; set; }

    public bool? Status { get; set; }

    [InverseProperty("Feedback")]
    public virtual ICollection<RefBogsFeedback> RefBogsFeedbacks { get; set; } = new List<RefBogsFeedback>();

    [InverseProperty("Feedback")]
    public virtual ICollection<RefFeedback> RefFeedbacks { get; set; } = new List<RefFeedback>();
}