// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObj.Models;

[PrimaryKey("OrderId", "ProductId")]
[Table("OrderDetail")]
public partial class OrderDetail
{
    [Key]
    [Column("OrderID")]
    [StringLength(20)]
    public string OrderId { get; set; }

    [Key]
    [Column("ProductID")]
    [StringLength(20)]
    public string ProductId { get; set; }

    public int Quantity { get; set; }

    public double Price { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderDetails")]
    public virtual Product Product { get; set; }
}