// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObj.Models;

[PrimaryKey("ProductId", "EnId")]
[Table("RefProductImg")]
public partial class RefProductImg
{
    [Key]
    [Column("ProductID")]
    [StringLength(20)]
    public string ProductId { get; set; }

    [Key]
    [Column("EnID")]
    [StringLength(20)]
    public string EnId { get; set; }

    public bool? Status { get; set; }

    [ForeignKey("EnId")]
    [InverseProperty("RefProductImgs")]
    public virtual Entertain En { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("RefProductImgs")]
    public virtual Product Product { get; set; }
}