// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObj.Models;

[PrimaryKey("ProductId", "AttributeId")]
[Table("RefProductAttribute")]
public partial class RefProductAttribute
{
    [Key]
    [Column("ProductID")]
    [StringLength(20)]
    public string ProductId { get; set; }

    [Key]
    [Column("AttributeID")]
    [StringLength(20)]
    public string AttributeId { get; set; }

    public bool? Status { get; set; }

    public int QuantityIn { get; set; }

    [ForeignKey("AttributeId")]
    [InverseProperty("RefProductAttributes")]
    public virtual Attribute Attribute { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("RefProductAttributes")]
    public virtual Product Product { get; set; }
}