// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObj.Models;

[Table("ShippingPrice")]
public partial class ShippingPrice
{
    [Key]
    [Column("ShippingID")]
    public int ShippingId { get; set; }

    [Column("Shipping_price")]
    public double ShippingPrice1 { get; set; }

    [Required]
    [Column("Location_name")]
    [StringLength(50)]
    public string LocationName { get; set; }

    [Column("Create_by")]
    [StringLength(20)]
    public string CreateBy { get; set; }

    [Column("Create_at", TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [Column("Update_by")]
    [StringLength(20)]
    public string UpdateBy { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Delete_by")]
    [StringLength(20)]
    public string DeleteBy { get; set; }

    [Column("Delete_at", TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    public bool? Status { get; set; }

    [InverseProperty("Location")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}