// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObj.Models;

[Table("Transaction")]
public partial class Transaction
{
    [Key]
    [Column("TransactionID")]
    [StringLength(100)]
    public string TransactionId { get; set; }

    [Required]
    [Column("OrderID")]
    [StringLength(20)]
    public string OrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Datetime { get; set; }

    [Column("Create_date", TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Required]
    [Column("Transaction_code")]
    [StringLength(50)]
    public string TransactionCode { get; set; }

    [Required]
    [Column("vpn_TransDate")]
    [StringLength(50)]
    public string VpnTransDate { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Transactions")]
    public virtual Order Order { get; set; }
}